############# English navigation ##############

# main menu
main:
  - name: Inici
    url: ca
    weight: 1
  - name: Qui som
    url: ca/qui-som
    weight: 2
  - name: Blog
    url: ca/blog
    weight: 3

# footer menu
footer:
  - name: Inici
    url: ca
    weight: 1
  - name: Qui som
    url: ca/qui-som
    weight: 2
  - name: Blog
    url: ca/blog
    weight: 3
